"""Module 8 — Init: generate .claude/CLAUDE.md for any Android project.

Auto-detects the project type (standard/Compose/KMP/CMP), package name,
and module layout, then writes a tailored CLAUDE.md that teaches Claude
Code how to use cab for that specific project.
"""

from __future__ import annotations

import os
from typing import Dict

from ddb.modules.build import detect
from ddb.utils.output import err, ok

# ------------------------------------------------------------------
# The template — filled in with project-specific values
# ------------------------------------------------------------------

_TEMPLATE = """\
# {project_name} — Android Development with ddb

> Auto-generated by `ddb init`. Edit freely — Claude Code reads this
> file every session to understand how to build, run, and test this app.

## Project Info

- **Type**: {project_type}
- **Package**: `{package_name}`
- **Android module**: `{android_module}`
{compose_line}{targets_line}

## Setup

`ddb` (Droid Debug Bridge) must be installed:
```bash
pip install ddb-tool    # or: pip install -e /path/to/ddb
ddb doctor              # verify adb, Java, SDK, device
ddb doctor --project .  # also check Gradle wrapper
```

## Core Workflow

After making code changes, follow this loop:

```bash
# 1. Build, install, and launch
ddb run --project . --package {package_name}

# 2. Wait for the app to settle
ddb wait-for --text "expected text" --timeout 5
{wait_for_tag_example}
# 3. Screenshot to verify UI
ddb screenshot

# 4. Check for errors
ddb logs --tag {log_tag} --level E --lines 30

# 5. Interact if needed
{uidump_command}
{tap_command}
```

## UI Inspection
{ui_section}

## Finding & Tapping Views

```bash
# By visible text (View or Compose)
ddb find --text "Login"
ddb tap-view --text "Login"
{compose_find_section}
```

## Logs & Debugging

```bash
ddb logs --tag {log_tag} --level E --lines 50
ddb logs --package {package_name} --grep "Exception"
ddb logs-clear                    # clear before a test run
ddb crash {package_name}          # get crash traces

# App data (debug builds)
ddb prefs {package_name}
ddb shell "dumpsys activity top"
```

## Full Feature Validation

When implementing a new feature end-to-end:

```bash
# 1. Detect project setup (first time)
ddb detect --project .

# 2. Build and deploy
ddb run --project . --package {package_name}

# 3. Navigate to the feature
ddb wait-for --text "Home" --timeout 10
{nav_example}

# 4. Screenshot & verify
ddb screenshot feature_screen.png
ddb logs --tag {log_tag} --lines 10

# 5. Test back navigation
ddb key BACK
ddb screenshot after_back.png
```

## Tips

- **Always screenshot after interactions** — this is how you "see" the app.
- **Use `wait-for` after navigation** — Compose recomposition takes time.
{compose_tips}- **Clear logs before testing** (`ddb logs-clear`) to reduce noise.
- **All output is JSON** — parse `"success"` to check results, read `"hint"` on errors.
- When a device isn't responding, run `ddb devices` to check connectivity.
"""


def init(project_dir: str, force: bool = False) -> Dict:
    """Generate .claude/CLAUDE.md with cab instructions tailored to this project.

    Auto-detects project type, package name, and module layout, then writes
    instructions that Claude Code will read automatically.

    Args:
        project_dir: Root of the Android/KMP/CMP project.
        force: If True, overwrite existing .claude/CLAUDE.md.
    """
    project_dir = os.path.abspath(project_dir)

    # Detect project
    detection = detect(project_dir)
    if not detection.get("success"):
        return detection  # propagate the error from detect()

    data = detection["data"]
    project_type = data.get("type", "standard")
    package_name = data.get("package_name") or "com.example.app"
    android_module = data.get("android_module") or "app"
    is_compose = data.get("has_compose", False)
    is_multiplatform = data.get("is_multiplatform", False)
    targets = data.get("targets", [])

    # Derive project name from directory
    project_name = os.path.basename(project_dir)

    # Derive a reasonable log tag from package name
    log_tag = package_name.split(".")[-1].capitalize() if package_name else "App"

    # Build template values
    type_label = {
        "standard": "Standard Android",
        "compose": "Jetpack Compose",
        "kmp": "Kotlin Multiplatform (KMP)",
        "cmp": "Compose Multiplatform (CMP)",
    }.get(project_type, project_type)

    compose_line = "- **Compose**: Yes\n" if is_compose else ""
    targets_line = f"- **Targets**: {', '.join(targets)}\n" if is_multiplatform and targets else ""

    # Compose-specific sections
    if is_compose:
        wait_for_tag_example = 'cab wait-for --tag "screen_tag" --timeout 5\n'
        uidump_command = "ddb uidump                            # auto-detects Compose"
        tap_command = 'cab tap-view --tag "compose_test_tag" # tap by Compose testTag'
        ui_section = """
```bash
# Auto mode (recommended) — switches to accessibility tree if Compose detected
ddb uidump

# Force Compose semantics (testTag, role, state)
ddb uidump --mode compose
ddb compose-tree

# Force traditional View hierarchy
ddb uidump --mode view

# Both merged (hybrid UIs)
ddb uidump --mode both
```
"""
        compose_find_section = """
# By Compose testTag (Modifier.testTag) — most reliable for Compose
ddb find --tag "btn_login"
ddb tap-view --tag "btn_login"

# By Compose semantic role
ddb find --role "Button"
"""
        nav_example = (
            'cab tap-view --tag "nav_settings"       # or --text "Settings"\n'
            'cab wait-for --tag "settings_screen"'
        )
        compose_tips = (
            "- **Prefer `--tag` over `--text` for Compose** — "
            "testTags are stable across locales.\n"
            '- **Add `Modifier.testTag("...")` to key UI elements** for reliable targeting.\n'
        )
    else:
        wait_for_tag_example = ""
        uidump_command = "ddb uidump                            # dump View hierarchy"
        tap_command = 'cab tap-view --text "Button Label"    # tap by text'
        ui_section = """
```bash
ddb uidump              # full View hierarchy as JSON
ddb uidump --full       # include all nodes (no filtering)
```
"""
        compose_find_section = """
# By resource ID
ddb find --id "com.example:id/btn_login"
ddb tap-view --id "com.example:id/btn_login"
"""
        nav_example = 'cab tap-view --text "Settings"\n' 'cab wait-for --text "Settings"'
        compose_tips = ""

    # Render the template
    content = _TEMPLATE.format(
        project_name=project_name,
        project_type=type_label,
        package_name=package_name,
        android_module=android_module,
        compose_line=compose_line,
        targets_line=targets_line,
        log_tag=log_tag,
        wait_for_tag_example=wait_for_tag_example,
        uidump_command=uidump_command,
        tap_command=tap_command,
        ui_section=ui_section,
        compose_find_section=compose_find_section,
        nav_example=nav_example,
        compose_tips=compose_tips,
    )

    # Write to .claude/CLAUDE.md
    claude_dir = os.path.join(project_dir, ".claude")
    output_path = os.path.join(claude_dir, "CLAUDE.md")

    if os.path.isfile(output_path) and not force:
        return err(
            f"File already exists: {output_path}",
            hint="Use --force to overwrite, or edit the file manually.",
        )

    os.makedirs(claude_dir, exist_ok=True)

    with open(output_path, "w") as f:
        f.write(content)

    return ok(
        {
            "path": output_path,
            "project_type": type_label,
            "package": package_name,
            "module": android_module,
            "compose": is_compose,
        },
        message=f"Created {output_path} — Claude Code will read this automatically.",
    )
